main: io.github.sinhajun.plugin.JavaPlugin
name: ${name}
version: '${version}'
api-version: 1.19
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.8.21
  - org.jetbrains.kotlin:kotlin-reflect:1.8.21
  - io.github.monun:kommand-core:3.1.6